name: Deploy

on:
    push:
        branches: ["master"]

jobs:
    my_buld_job:
        runs-on: ubuntu-latest
        steps:
            - run: ssh kolka@45.140.179.214
            - run: ls
            - run: exit
