name: Deploy

on:
    push:
        branches: ["master"]

jobs:
    my_buld_job:
        - name: multiple command
        uses: appleboy/ssh-action@master
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            script: |